# Generated by Django 5.0.3 on 2024-04-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyectos_tareas'),
        ('tareas', '0005_alter_entrada_historial_tarea_delete_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
    ]
