# Generated by Django 5.0.3 on 2024-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_rename_tarea_entrada_historial_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada_historial',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
