# Generated by Django 5.0.3 on 2024-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0006_remove_user_grupo_user_telefono'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_grupo_set', to='auth.group'),
        ),
    ]
