# Generated by Django 5.0.3 on 2024-05-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0007_user_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupo',
        ),
    ]
