# Generated by Django 5.0.3 on 2024-04-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('tareas', '0005_alter_entrada_historial_tarea_delete_proyectos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
