# Generated by Django 5.0.3 on 2024-04-12 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descrip', models.TextField(max_length=500)),
                ('estado', models.IntegerField(choices=[(0, 'Sin asignar'), (1, 'Asignado/Sin iniciar'), (2, 'En proceso'), (3, 'Hecho')], default=0)),
                ('fecha_entrega', models.DateField(default=None)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('resumen', models.TextField(max_length=1000)),
                ('adjunto', models.FileField(blank=True, upload_to='archivos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, upload_to='<tarea.nombre>/archivos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualización', models.DateTimeField(auto_now=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas')),
            ],
        ),
    ]
