# Generated by Django 5.0.3 on 2024-04-12 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tareas_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Sin asignar'), (1, 'Asignado/Sin iniciar'), (2, 'En proceso'), (3, 'Hecho'), (4, 'En pausa'), (5, 'Cancelado')], default=0),
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tareas', models.ManyToManyField(blank=True, to='tareas.tareas')),
            ],
        ),
        migrations.AlterField(
            model_name='entrada_historial',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.proyectos'),
        ),
    ]
