# Generated by Django 5.0.3 on 2024-04-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('tareas', '0003_alter_tareas_estado_proyectos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
