# Generated by Django 5.0.3 on 2024-04-12 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('tareas', '0004_proyectos_cliente_proyectos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada_historial',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
