# Generated by Django 5.0.3 on 2024-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_tareas_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada_historial',
            old_name='tarea',
            new_name='proyecto',
        ),
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, upload_to='archivos/'),
        ),
    ]
