# Generated by Django 5.0.3 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_alter_tareas_encargado_alter_tareas_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
