# Generated by Django 5.0.3 on 2024-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_alter_archivos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='entrada_historial',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
