# Generated by Django 5.0.3 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_alter_archivos_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_historial',
            name='fecha',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
