# Generated by Django 5.0.3 on 2024-04-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada_historial',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='encargado',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.DeleteModel(
            name='Entrada_historial',
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
