# Generated by Django 5.0.3 on 2024-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyectos_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='n_expediente',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
