# Generated by Django 5.0.3 on 2024-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyectos_n_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='n_expediente',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
